package app.reddot.model;

import app.reddot.util.AppUserRole;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import javax.persistence.*;

@Getter
@Setter
@EqualsAndHashCode
@Entity
@Table(name = "users")
@Data
public class AppUser {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id; //Id is autogenerated
    @Column(nullable = false)
    private String username; //pseudonyme
    @Column(nullable = false)
    private String password; //mot de passe

    //private AppUserRole role; //user or admin?

    public AppUser() {} //no args constructor

    //USERNAME ====================
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    //PASSWORD ====================
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    //ID =========================
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    //ROLE =======================
//    public AppUserRole getRole() {
//        return role;
//    }
//    public void setRole(AppUserRole role) {
//        this.role = role;
//    }
}
